name: checks
description: "Template that runs pre-commit hooks"

inputs:
    python_version:
        description: "Python version to use."
        required: false
        default: "3.11"
    pre_commit_version:
        description: "Pre-commit version to use."
        required: false
        default: "3.1.1"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Create virtual environment
      run: python3 -m venv venv && source venv/bin/activate
      shell: bash
    - name: Install pre-commit
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pre-commit==${{ inputs.pre_commit_version }}
      shell: bash
    - name: Cache pre-commit
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
